### ISSUE TITLE
Web Proxy

### ISSUE THREAD

**Issue by ardhiee** [jpbarto/private-eks-cluster#2]
Hi could you explain more for web proxy, which api that i need to pointing

**Comment by tomellis** [comment]
Hi Ardi,

I was actually just working on some enhancements to this repo including updating the README to explain the proxy part in more detail. It was assumed you have one of these already somewhere in AWS and expose it via a VPC Endpoint Service.  Then in variables.sh you point it to the DNS name provided by the service. 

If you checkout my branch here:
https://github.com/tomellis/private-eks-cluster/tree/fargate-support
There is an example within the README and cloudformation/proxy.yaml.

HTH

**Comment by tomellis** [comment]
Hi @ardhiee 
The template is now merged into the repo and you should find additional instructions in the README.

Thanks!

Tom
